<script>
function checkrequired(which){
var pass=true
if (document.images){
for (i=0;i<which.length;i++){
var tempobj=which.elements[i]
if (tempobj.name.substring(0,8)=="required"){
if (((tempobj.type=="text"||tempobj.type=="textarea")&&tempobj.value=='')||(tempobj.type.toString().charAt(0)=="s"&&tempobj.selectedIndex==-1)){
pass=false
break
}
}
}
}
if (!pass){
alert("Todos los campos del formulario deben ser digitados !!!!")
return false
}
else
return true
}
</script>
<?php   View::content();    ?>
<h2>Actualizar datos de Jefe de Progma</h2>
<?php echo form_tag('jefeprograma/actualizarJefePrograma/',"onSubmit: return checkrequired(this)");?>
<table>
    <tbody>
        <tr>
            <td>codigo</td>
            <td><input type="text" name="usuario[cod]" value="<?php echo $usuario->cod;?>" readonly="readonly" /></td>
        </tr>
        <tr>
            <td>nombre</td>
            <td><?php echo textupper_field_tag('requirednombre')?></td>
        </tr>
        <tr>
            <td>primer apellido</td>
            <td><?php echo textupper_field_tag('requiredp_apellido')?></td>
        </tr>
        <tr>
            <td>segundo apellido</td>
            <td><?php echo textupper_field_tag('requireds_apellido')?></td>
        </tr>
        <tr>
            <td>user name</td>
            <td><?php echo text_field_tag('requireduser_name')?></td>
        </tr>
        <tr>
            <td>password</td>
            <td><?php echo password_field_tag('requiredpass')?></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td><?php echo text_field_tag('requiredemail')?></td>
        </tr>
        <tr>
             <td>programa</td>
            <td>
                <select name="usuario[programa_id]">
                    <option value="<?php echo $usuario->programa_id;?>">Seleccione una Opcion</option>
                    <?php foreach($programa as $programas){
                           echo "<option value= \"$programas->id\">$programas->nombre</option>\n";
                        }?>
                </select>
            </td>
        </tr>
        <tr>
            <td><?php echo submit_tag('guardar') ?><input type="button" value="Cancelar" onclick="" /></td>
        </tr>
    </tbody>
</table>
<?php echo end_form_tag()?>

