<?php View::content();
$letras = array();
$letras[1]= "A";
$letras[2]= "B";
$letras[3]= "C";
$letras[4]= "D";
?>
<div class="fondo">
<?php echo form_tag("respuesta/pregunta/$examen_id")?>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <?php foreach($pregunta as $preguntas){?>
    <tr>
      <th colspan="4" align="justify"><p><?php echo $preguntas->texto?></p></th>
    </tr>
    <tr>
      <td colspan="4">&nbsp;</td>
    </tr>
    <?php foreach($opciones[$preguntas->id] as $opcion){?>
    <tr>
      <td colspan="4"><p><?php echo $letras[$opcion['opcion']].")    ".$opcion['texto']?></p></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <?php }?>
    
    <tr>
    <?php foreach($opciones[$preguntas->id] as $opcion){?>
      <td width="25%">
        <label><?php echo $letras[$opcion['opcion']]?> ->
            <input type="radio" name="preguntas[<?=$preguntas->id?>]" id="uno" value="<?=$opcion['opcion']?>" />
        </label>
      </td>
    <?php }?>
    </tr>
    <tr>
        <td colspan="4" bgcolor="#D8D8D8">&nbsp;</td>
    </tr>
    <?}?>
    <tr>
        <td colspan="4" align="center"><?php echo submit_tag("Siguiente")?></td>
    </tr>
  </table>
  <?php echo end_form_tag();?>
 </div>

  