
<?php

$cadena = array();
foreach ($serie as $key=>$value)
{
    $cadena[$key] = "{ name: 'Examen $key', data:  [".implode(",", $value)."]}";
}
?>
<div id="progreso"></div>
<script type="text/javascript">

    var chart;

    chart = new Highcharts.Chart({
        chart: {
            renderTo: 'progreso',
            defaultSeriesType: 'column'
        },
        title: {
            text: 'Progreso Estudiante Por Area Tematica'
        },
        subtitle: {
            text: '%buenas / Area Tematica'
        },
        xAxis: {
            categories: [<?echo implode(",", $areas)?>
            ],
            title: {
                text: 'Areas Tematicas'
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: '% Buenas'
            }
        },
        legend: {
            layout: 'vertical',
            backgroundColor: '#FFFFFF',
            align: 'left',
            verticalAlign: 'top',
            x: 100,
            y: 70,
            floating: true,
            shadow: true
        },
        tooltip: {
            formatter: function() {
                return 'Examen '+
                    this.x +': '+ this.y +' %';
            }
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [<?echo implode(",", $cadena)?>]
    });

</script>