<?php
echo View::content();
?>
<div id="areaTrabajoEstudiante" style="max-height: 400px; overflow: scroll;margin-top: 10px">
    <table cellspacing="1" cellpadding="0" border="0" width="100%" >
    <?if ($resultado != null){?>
    <thead>
        <tr>
            <th>Examen</th>
            <th>Area Tematica</th>
            <th>Buenas</th>
            <th>Malas</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
    <?php $i= true;
    foreach($resultado as $paginas){?>
        <tr bgcolor="<?php echo ($i)? '#CCDEFF':'#FFFFFF';?>" align="center">
            <td><?echo $paginas["examen"]?></td>
            <td><?echo $paginas["areatematica"];?></td>
            <td><?echo $paginas["buenas"]?></td>
            <td><?echo $paginas["malas"]?></td>
            <td><?echo $paginas["total"]?></td>
        </tr>
    <?php $i=($i)? false:true; }?>
    </tbody>
    <?}?>
</table>
</div>
<h2><?echo link_to_remote("Ver Grafica Examen", "action: sigEstudiante/mostrarGraficaExamen/$cod", "update: areaTrabajoEstudiante")?></h2>
<br>
<h2><?echo link_to_remote("Ver Grafica Areas", "action: sigEstudiante/mostrarGraficaArea/$cod", "update: areaTrabajoEstudiante")?></h2>