<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<style type="text/css">
#menuPrincipal{
	float: left;
	margin: .5em .5em .5em .5em;
}

#areaTrabajo{
    float: left;
    clear: none;
    margin: .5em .5em .5em .5em;
    min-height: 800px;
    min-width: 800px;
}
</style>
<h2>SISTEMA DE INFORMACION - SIMULADOR DE ECAES</h2>
<div id="menuPrincipal"><?echo View::partial("menuPrincipalSistemaInformacion")?></div>
<div id="areaTrabajo"><span>Sistema de Informaion Para UdeCEcaes</span></div>