<?php
View::content();
?>

<div style="margin: 1em 1em 1em 1em"><?echo form_remote_tag("sigPrograma/estadisticasResultadosExamen", "update: areaTrabajoPrograma", "method: post")?>
    <label>Examen: </label>
    <?echo select_tag("examen_id")?>
    <?echo option_tag(0, "seleccione...")?>
    <?foreach($resultado2 as $result)
    {?>
        <?echo option_tag($result["examen"], $result["examen"])?>
        <?}?>
    <?echo submit_tag("Buscar")?>
<?echo end_form_tag()?>
</div>
<div id="tableroTrabajoPrograma">
    <table cellspacing="1" cellpadding="0" border="0" width="100%" >
<?if ($resultado != null)
{?>
        <thead>
            <tr>
                <th>Examen</th>
                <th>Buenas</th>
                <th>Malas</th>
                <th>Total</th>
                <th>% Buenas</th>
                <th>% Malas</th>
                <th>Indice de Buenas / Malas</th>
                <th>Indice de Malas / Buenas</th>
                <th>Area Tematica</th>
            </tr>
        </thead>
        <tbody>
    <?php $i= true;
    foreach($resultado as $paginas)
    {?>
            <tr bgcolor="<?php echo ($i)? '#CCDEFF':'#FFFFFF';?>" align="center">
                <td><?echo $paginas["examen"]?></td>
                <td><?echo $paginas["cant_buenas"]?></td>
                <td><?echo $paginas["cant_malas"]?></td>
                <td><?echo $paginas["total_respuestas"]?></td>
                <td><?echo $paginas["porcentaje_buenas"]*100?></td>
                <td><?echo $paginas["porcentaje_malas"]*100?></td>
                <td><?echo $paginas["indice_bm"]?></td>
                <td><?echo $paginas["indice_mb"]?></td>
                <td><?echo $paginas["areatematica"];?></td>
            </tr>
        <?php $i=($i)? false:true;
    }?>
        </tbody>
    <?}?>
    </table>
    </div>
<?if($resultado != null){?>
<?echo link_to_remote("Ver Grafica De Resultados", "update: tableroTrabajoPrograma", "action: sigPrograma/mostrarGrafica/$examen_id")?>
<br>
<?echo link_to_remote("Ver Grafica De Porcentajes", "update: tableroTrabajoPrograma", "action: sigPrograma/mostrarGraficaPorcentaje/$examen_id")?>
<?}?>