<style>
#intro{
    color:black;
    font-size:17px;
}
</style>
<?php

?>
<br>
<h2>Bienvenido Estudiante <?php echo $_SESSION["nombre"];?></h2>
<br>

<p id="intro" align="justify">UdeC-Ecaes es una plataforma virtual diseñada con el objetivo de que los estudiantes conozcan a un poco
mas a fondo lo que se refiere a realizar el examen de calidad de la eduacion superior, mayormente conocido
como pruebas ECAES.
<br>
<br>
Este sitio web ofrece el servicio de simulacion de dichas pruebas con el fin de entrenar a los estudiantes
y  que estos adquieran una experiencia previa y destreza para lograr alcanzar puestos de reconocimiento a nivel nacional.
</p>
