<script>
function checkrequired(which){
var pass=true
if (document.images){
for (i=0;i<which.length;i++){
var tempobj=which.elements[i]
if (tempobj.name.substring(0,8)=="required"){
if (((tempobj.type=="text"||tempobj.type=="textarea")&&tempobj.value=='')||(tempobj.type.toString().charAt(0)=="s"&&tempobj.selectedIndex==-1)){
pass=false
break
}
}
}
}
if (!pass){
alert("Todos los campos del formulario deben ser digitados !!!!")
return false
}
else
return true
}
</script>
<h2>Registro</h2>
<?php View::content();?>
<?php if(!$aux){?>
<?php echo form_tag('estudiante/registrarEstudiante/',"onSubmit: return checkrequired(this)");?>
<table>
    <tbody>
        <tr>
            <td>codigo</td>
            <td><?php echo numeric_field_tag('requiredusuario.cod')?></td>
        </tr>
        <tr>
            <td>nombre</td>
            <td><?php echo textupper_field_tag('requiredusuario.nombre')?></td>
        </tr>
        <tr>
            <td>primer apellido</td>
            <td><?php echo textupper_field_tag('requiredusuario.p_apellido')?></td>
        </tr>
        <tr>
            <td>segundo apellido</td>
            <td><?php echo textupper_field_tag('requiredusuario.s_apellido')?></td>
        </tr>
        <tr>
            <td>user name</td>
            <td><?php echo text_field_tag('requiredusuario.user_name')?></td>
        </tr>
        <tr>
            <td>password</td>
            <td><?php echo password_field_tag('requiredusuario.pass')?></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td><?php echo text_field_tag('requiredusuario.email')?></td>
        </tr>
        <tr>
             <td>programa</td>
            <td>
                <select name="requiredusuario[programa_id]">
                    <option value="0">Seleccione una Opcion</option>
                    <?php foreach($programa as $programas){
                           echo "<option value= \"$programas->id\">$programas->nombre</option>\n";
                        }?>
                </select>
            </td>
        </tr>
        <tr>
            <td>Semestre</td>
            <td><?php echo numeric_field_tag('requiredusuario.sem');?></td>
        </tr>
        <tr>
            <td><?php echo submit_tag('guardar') ?><input type="button" value="Cancelar" onclick="" /></td>
        </tr>
    </tbody>
</table>
<?php echo end_form_tag()?>
<?php }else{
    echo link_to("reactivarcuenta", "Reactivar mi cuenta");
}
?>